#  docker build -f Dockerfile -t meenibatch/ai-py-app:latest .
# docker push meenibatch/ai-py-app:latest

# docker build -f Dockerfile -t pyapp .
FROM python:latest

WORKDIR /app

#RUN mkdir -p /static_folder
#COPY ./static_html /static_folder
COPY ./src .
#RUN echo "hello world" > index.html

# python -m http.server 8000
# docker run -t -p 8080:8000
CMD ["python", "-m", "http.server", "8000"]